apiVersion: v1
kind: Service
metadata:
  name: trend-app-service
spec:
  selector:
    app: trend-app        # Must match the label in your Deployment
  ports:
    - protocol: TCP
      port: 80          # Port exposed outside the cluster (like -p 3000)
      targetPort: 3000      # Container port (the port your app listens on)
  type: NodePort           # Use NodePort if you want to access via cluster nodes
