apiVersion: v1
kind: Service
metadata:
  name: trend-app-service
  labels:
    app: trend-app
spec:
  type: LoadBalancer
  selector:
    app: trend-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
