apiVersion: v1
kind: Service
metadata:
  name: trend-app-service
spec:
  selector:
    app: trend-app
  ports:
    - protocol: TCP
      port: 80        # Exposed port on the LoadBalancer
      targetPort: 3000  # Container port where your app is running
  type: LoadBalancer
